local computer = require("computer")
os.execute("clear")
os.sleep(1)
local total = computer.totalMemory()
print("Total memory:")
print(total.." Byte")
print(total/1024 .." KiloByte")
print(total/1048576 .." MegaByte\n")

os.sleep(1)
local free = computer.freeMemory()
print("Free memory:")
print(free.." Byte")
print(free/1024 .." KiloByte")
print(free/1048576 .." MegaByte\n")

os.sleep(1)
print("Memory used:")
print(string.format("%i%% memory is used", math.floor((1-(free/total))*100 + 0.5)))
print(total-free .." Byte")
print((total-free)/1024 .." KiloByte")
print((total-free)/1048576 .." MegaByte")
